# DATA CLEANING

In [2]:
import pandas as pd
import numpy as np

data_set = pd.read_csv('airbnb_lisbon_1480_2017-07-27.csv')
data_set.head()

data_set2 = data_set.apply(lambda x: x.astype(str).str.lower()) #this converts dataframe to lowercase
col_to_drop = ["country", "borough", "room_id", "survey_id", "host_id", "bathrooms", "minstay", "last_modified","latitude","longitude","location"]
my_data = data_set2.drop(col_to_drop, axis=1)
my_data[['reviews','overall_satisfaction','price']] = my_data[['reviews','overall_satisfaction','price']].astype('float')
#my_data.dtypes


#dropped_col_data = dropped_col_data[dropped_col_data.reviews !=0]
new_data = my_data[my_data["reviews"] != 0]

new_data.tail(20)
new_data.to_csv('cleaned_data.csv', index=False)

# IMPORT CLEAN DATA

In [2]:
import pandas as pd
import numpy as np

clean_data = pd.read_csv('cleaned_data.csv')
print(clean_data.head())

print(clean_data.mean(axis=0))
print(clean_data.max(axis=0))
print(clean_data.std(axis=0))
print(clean_data.median(axis=0))

     room_type    city       neighborhood  reviews  overall_satisfaction  \
0  shared room  lisbon      santo antónio     19.0                   4.5   
1  shared room  lisbon     avenidas novas      4.0                   3.5   
2  shared room  lisbon  santa maria maior     38.0                   4.5   
3  shared room  lisbon     avenidas novas      9.0                   4.0   
4  shared room  lisbon            arroios      1.0                   0.0   

   accommodates  bedrooms  price                                         name  
0             4       1.0   30.0   low cost hostel marques gardens 4 bed dorm  
1             6       1.0   39.0                        room in lisbon center  
2             8       1.0   39.0  bed in a 8-bed dorm @ this is lisbon hostel  
3             6       1.0   37.0                  shared mixed bunkbed room 1  
4             2       1.0   96.0                              nice room anjos  
reviews                 35.814159
overall_satisfaction     3.93

In [3]:
clean_data = clean_data[clean_data["reviews"] > 35]
print(clean_data.mean(axis=0))
#clean_data.tail()

reviews                 85.260086
overall_satisfaction     4.664067
accommodates             4.014524
bedrooms                 1.505648
price                   72.728080
dtype: float64


# DATA FOR RATINGS

In [4]:
drop_list = ["city", "accommodates", "name", "room_type", "bedrooms", "price"]
ratings = clean_data.drop(drop_list, axis = 1)

ratings['Normalized Review Quantity'] = (((ratings['reviews']-min(ratings['reviews']))/(max(ratings['reviews'])-min(ratings['reviews'])))*5)
ratings['ratings_weight'] = (ratings['Normalized Review Quantity']*.5) + (ratings['overall_satisfaction']*.5)
ratings.sort_values(['Normalized Review Quantity'], ascending = False)

ratings_agg = round((ratings.groupby(['neighborhood']).agg(['mean'])),2)
ratings_agg["reviews"] = ratings_agg['reviews'].astype('int')
ratings_agg = ratings_agg.reset_index(level = 0)
ratings_agg.columns = ["Neighborhood", "AVG Reviews / Listing", "AVG User Rating","Normalized Review Quantity", "Weighted Ratings"]
ratings_agg["Rank"] = ratings_agg['Weighted Ratings'].rank(ascending = False).astype('int')
ratings_agg = ratings_agg[['Rank',"Neighborhood","Weighted Ratings", "AVG User Rating", "AVG Reviews / Listing","Normalized Review Quantity"]]
#ratings_agg.head(50)
ratings_agg.sort_values(["Rank"],ascending = True)

# ratings_mean.sort_values(['overall_satisfaction'], ascending=False)

Rank             Neighborhood  Weighted Ratings  AVG User Rating  \
15     1                  olivais              2.81             4.64   
18     2        santa maria maior              2.68             4.67   
14     3             misericórdia              2.65             4.66   
19     4            santo antónio              2.61             4.69   
8      5                  benfica              2.60             5.00   
11     5                  estrela              2.60             4.66   
21     8              são vicente              2.59             4.62   
4      8                  arroios              2.59             4.67   
2      8                 alvalade              2.59             4.68   
5     10           avenidas novas              2.58             4.74   
1     11                alcântara              2.57             4.61   
3     12                  areeiro              2.55             4.71   
9     13         campo de ourique              2.54             4.67   
17    13          penha de frança              2.54             4.64   
7     15                    belém              2.53             4.65   
12    15                   lumiar              2.53             4.85   
20    17  são domingos de benfica              2.52             4.75   
10    18                campolide              2.46             4.64   
16    19        parque das nações              2.42             4.67   
0     19                    ajuda              2.42             4.56   
6     21                    beato              2.37             4.50   
13    22                  marvila              2.31             4.43   

    AVG Reviews / Listing  Normalized Review Quantity  
15                    116                        0.98  
18                     92                        0.69  
14                     89                        0.65  
19                     79                        0.53  
8                      52                        0.19  
11                     79                        0.53  
21                     81                        0.55  
4                      77                        0.51  
2                      77                        0.50  
5                      70                        0.42  
1                      79                        0.53  
3                      68                        0.39  
9                      69                        0.41  
17                     71                        0.43  
7                      70                        0.42  
12                     53                        0.22  
20                     60                        0.30  
10                     58                        0.27  
16                     49                        0.17  
0                      58                        0.28  
6                      56                        0.25  
13                     51                        0.19

# DATA FOR PRICE

In [7]:
drop_list = ["city", "accommodates", "name", "reviews", "overall_satisfaction","room_type"]
price = clean_data.drop(drop_list, axis = 1)
price['bedrooms'] = price['bedrooms'].map(lambda x: 1 if x==0 else x)
price['price/br'] = (price['price']*.9)/price["bedrooms"]
drop_price = ["price","bedrooms"]
price = price.drop(drop_price, axis = 1)
price_agg = round(price.groupby(['neighborhood']).agg(['mean']),2)
price_agg = price_agg.reset_index(level = 0)
price_agg.columns = ["Neighborhood","Price / BR (€)"]
price_agg["Rank"] = price_agg['Price / BR (€)'].rank(ascending = True).astype('int')
price_agg = price_agg[["Rank","Neighborhood","Price / BR (€)"]]
price_agg.sort_values('Price / BR (€)',ascending=False)



#price.groupby(['neighborhood']).agg(['mean'])
#price.head(100)

Rank             Neighborhood  Price / BR (€)
18    22        santa maria maior           49.24
5     21           avenidas novas           48.39
14    20             misericórdia           47.32
16    19        parque das nações           47.30
11    18                  estrela           45.33
19    17            santo antónio           45.16
9     16         campo de ourique           44.80
21    15              são vicente           43.30
20    14  são domingos de benfica           40.46
4     13                  arroios           37.17
7     12                    belém           36.75
1     11                alcântara           36.42
0     10                    ajuda           36.39
3      9                  areeiro           35.19
2      8                 alvalade           34.66
10     7                campolide           33.43
17     6          penha de frança           33.27
6      5                    beato           32.00
12     4                   lumiar           30.29
8      3                  benfica           29.10
15     2                  olivais           28.90
13     1                  marvila           23.85

# MERGE RATINGS & PRICE

In [8]:
ratings_price_agg = ratings_agg.merge(price_agg, on = 'Neighborhood')
ratings_price_agg.columns = ["Ratings Rank","Neighborhood","Weighted Ratings","Normalized Review Quantity", "AVG Reviews / Listing","AVG User Rating","Price Rank","Price / BR (€)"]
ratings_price_agg.sort_values("Ratings Rank")

Ratings Rank             Neighborhood  Weighted Ratings  \
15             1                  olivais              2.81   
18             2        santa maria maior              2.68   
14             3             misericórdia              2.65   
19             4            santo antónio              2.61   
8              5                  benfica              2.60   
11             5                  estrela              2.60   
21             8              são vicente              2.59   
4              8                  arroios              2.59   
2              8                 alvalade              2.59   
5             10           avenidas novas              2.58   
1             11                alcântara              2.57   
3             12                  areeiro              2.55   
9             13         campo de ourique              2.54   
17            13          penha de frança              2.54   
7             15                    belém              2.53   
12            15                   lumiar              2.53   
20            17  são domingos de benfica              2.52   
10            18                campolide              2.46   
16            19        parque das nações              2.42   
0             19                    ajuda              2.42   
6             21                    beato              2.37   
13            22                  marvila              2.31   

    Normalized Review Quantity  AVG Reviews / Listing  AVG User Rating  \
15                        4.64                    116             0.98   
18                        4.67                     92             0.69   
14                        4.66                     89             0.65   
19                        4.69                     79             0.53   
8                         5.00                     52             0.19   
11                        4.66                     79             0.53   
21                        4.62                     81             0.55   
4                         4.67                     77             0.51   
2                         4.68                     77             0.50   
5                         4.74                     70             0.42   
1                         4.61                     79             0.53   
3                         4.71                     68             0.39   
9                         4.67                     69             0.41   
17                        4.64                     71             0.43   
7                         4.65                     70             0.42   
12                        4.85                     53             0.22   
20                        4.75                     60             0.30   
10                        4.64                     58             0.27   
16                        4.67                     49             0.17   
0                         4.56                     58             0.28   
6                         4.50                     56             0.25   
13                        4.43                     51             0.19   

    Price Rank  Price / BR (€)  
15           2           28.90  
18          22           49.24  
14          20           47.32  
19          17           45.16  
8            3           29.10  
11          18           45.33  
21          15           43.30  
4           13           37.17  
2            8           34.66  
5           21           48.39  
1           11           36.42  
3            9           35.19  
9           16           44.80  
17           6           33.27  
7           12           36.75  
12           4           30.29  
20          14           40.46  
10           7           33.43  
16          19           47.30  
0           10           36.39  
6            5           32.00  
13           1           23.85

In [109]:
ratings_price_agg["Weighted Ratings"].corr(ratings_price_agg["Price / BR"])

0.2836051807427849

# --------------------------------------------------------------------------------------------------

# BAG OF WORDS

In [6]:
clean_data.head()

room_type    city       neighborhood  reviews  overall_satisfaction  \
0  shared room  lisbon      santo antónio     19.0                   4.5   
1  shared room  lisbon     avenidas novas      4.0                   3.5   
2  shared room  lisbon  santa maria maior     38.0                   4.5   
3  shared room  lisbon     avenidas novas      9.0                   4.0   
4  shared room  lisbon            arroios      1.0                   0.0   

   accommodates  bedrooms  price                                         name  
0             4       1.0   30.0   low cost hostel marques gardens 4 bed dorm  
1             6       1.0   39.0                        room in lisbon center  
2             8       1.0   39.0  bed in a 8-bed dorm @ this is lisbon hostel  
3             6       1.0   37.0                  shared mixed bunkbed room 1  
4             2       1.0   96.0                              nice room anjos

In [164]:
drop_list = ["city", "accommodates", "room_type", "bedrooms", "price"]
bow_ratings = clean_data.drop(drop_list, axis = 1)

bow_ratings['Normalized Review Quantity'] = (((bow_ratings['reviews']-min(bow_ratings['reviews']))/(max(bow_ratings['reviews'])-min(bow_ratings['reviews'])))*5)
bow_ratings['ratings_weight'] = (bow_ratings['Normalized Review Quantity']*.5) + (bow_ratings['overall_satisfaction']*.5)
bow_ratings.sort_values(['ratings_weight'], ascending = False)

#bow_ratings['ratings_weight'] = (ratings['reviews']*(0.4)) + (ratings['overall_satisfaction']*(0.6))
#bow_ratings.sort_values('ratings_weight', ascending = False).head()

# Limit to weighting over 100
ratings_100 = bow_ratings[(bow_ratings["ratings_weight"] > 2) & (bow_ratings['neighborhood'] == 'olivais')]
ratings_100.head(200)

neighborhood  reviews  overall_satisfaction  \
173        olivais    438.0                   4.5   
187        olivais    116.0                   4.5   
3548       olivais    145.0                   4.5   
6161       olivais     71.0                   4.5   
8205       olivais     68.0                   4.5   
10813      olivais     47.0                   4.5   
10816      olivais    160.0                   5.0   
10900      olivais    175.0                   5.0   
10903      olivais     48.0                   4.5   
10932      olivais    114.0                   4.5   
10933      olivais     37.0                   4.5   
10939      olivais     40.0                   5.0   
10940      olivais     39.0                   4.5   
10954      olivais    111.0                   4.5   
10956      olivais     43.0                   5.0   
10957      olivais     67.0                   5.0   
10970      olivais     40.0                   5.0   
11091      olivais     75.0                   4.5   
11105      olivais    125.0                   4.5   
11116      olivais    334.0                   4.5   
11144      olivais    162.0                   4.5   
11157      olivais    114.0                   4.5   

                                                    name  \
173                   open space in lisbon close airport   
187                  lisboa junto à expo/gare do oriente   
3548                          beautiful apt in expo area   
6161                     encarnação - lisboa, 2 quartos    
8205                  lisboa,1bd near aeroporto/p.nações   
10813                 cosy apartment near lisbon airport   
10816                       lisbon - bedroom + breakfast   
10900                       room with bathroom in lisbon   
10903      private third floor + kitchen and living room   
10932           lisbon private double room (2km airport)   
10933          lisbon private room two beds near airport   
10939               private room + kitchen + living room   
10940          próximo do aeroporto/ next to the airport   
10954                   luminoso espaço e verde em redor   
10956             private room + kitchen and living room   
10957  suite+privat bathr.-amazing lisb view-near air...   
10970               cozy room close to airport/meo arena   
11091             room near aiport (2km) with subway/bus   
11105        private room near the airport + kitchen use   
11116                         pleasant and much sympathy   
11144            room with private bathroom near airport   
11157                   quiet rooms close to the airport   

       Normalized Review Quantity  ratings_weight  
173                      4.878641        4.689320  
187                      0.970874        2.735437  
3548                     1.322816        2.911408  
6161                     0.424757        2.462379  
8205                     0.388350        2.444175  
10813                    0.133495        2.316748  
10816                    1.504854        3.252427  
10900                    1.686893        3.343447  
10903                    0.145631        2.322816  
10932                    0.946602        2.723301  
10933                    0.012136        2.256068  
10939                    0.048544        2.524272  
10940                    0.036408        2.268204  
10954                    0.910194        2.705097  
10956                    0.084951        2.542476  
10957                    0.376214        2.688107  
10970                    0.048544        2.524272  
11091                    0.473301        2.486650  
11105                    1.080097        2.790049  
11116                    3.616505        4.058252  
11144                    1.529126        3.014563  
11157                    0.946602        2.723301

In [165]:
corpus = ratings_100["name"].values
corpus


array(['open space in lisbon close airport',
       'lisboa junto à expo/gare do oriente',
       'beautiful apt in expo area', 'encarnação - lisboa, 2 quartos ',
       'lisboa,1bd near aeroporto/p.nações',
       'cosy apartment near lisbon airport',
       'lisbon - bedroom + breakfast', 'room with bathroom in lisbon',
       'private third floor + kitchen and living room',
       'lisbon private double room (2km airport)',
       'lisbon private room two beds near airport',
       'private room + kitchen + living room',
       'próximo do aeroporto/ next to the airport',
       'luminoso espaço e verde em redor',
       'private room + kitchen and living room',
       'suite+privat bathr.-amazing lisb view-near airport',
       'cozy room close to airport/meo arena',
       'room near aiport (2km) with subway/bus',
       'private room near the airport + kitchen use',
       'pleasant and much sympathy',
       'room with private bathroom near airport',
       'quiet rooms close to

In [166]:
import sklearn.feature_extraction.text
from sklearn.feature_extraction.text import CountVectorizer

stop_words = ['all', 'six', 'less', 'being', 'indeed', 'over', 'move', 'anyway', 'fifty', 'four', 'not', 'own', 'through', 'yourselves', 'go', 'where', 'mill', 'only', 'find', 'before', 'one', 'whose', 'system', 'how', 'somewhere', 'with', 'thick', 'show', 'had', 'enough', 'should', 'to', 'must', 'whom', 'seeming', 'under', 'ours', 'has', 'might', 'thereafter', 'latterly', 'do', 'them', 'his', 'around', 'than', 'get', 'very', 'de', 'none', 'cannot', 'every', 'whether', 'they', 'front', 'during', 'thus', 'now', 'him', 'nor', 'name', 'several', 'hereafter', 'always', 'who', 'cry', 'whither', 'this', 'someone', 'either', 'each', 'become', 'thereupon', 'sometime', 'side', 'two', 'therein', 'twelve', 'because', 'often', 'ten', 'our', 'eg', 'some', 'back', 'up', 'namely', 'towards', 'are', 'further', 'beyond', 'ourselves', 'yet', 'out', 'even', 'will', 'what', 'still', 'for', 'bottom', 'mine', 'since', 'please', 'forty', 'per', 'its', 'everything', 'behind', 'un', 'above', 'between', 'it', 'neither', 'seemed', 'ever', 'across', 'she', 'somehow', 'be', 'we', 'full', 'never', 'sixty', 'however', 'here', 'otherwise', 'were', 'whereupon', 'nowhere', 'although', 'found', 'alone', 're', 'along', 'fifteen', 'by', 'both', 'about', 'last', 'would', 'anything', 'via', 'many', 'could', 'thence', 'put', 'against', 'keep', 'etc', 'amount', 'became', 'ltd', 'hence', 'onto', 'or', 'con', 'among', 'already', 'co', 'afterwards', 'formerly', 'within', 'seems', 'into', 'others', 'while', 'whatever', 'except', 'down', 'hers', 'everyone', 'done', 'least', 'another', 'whoever', 'moreover', 'couldnt', 'throughout', 'anyhow', 'yourself', 'three', 'from', 'her', 'few', 'together', 'top', 'there', 'due', 'been', 'next', 'anyone', 'eleven', 'much', 'call', 'therefore', 'interest', 'then', 'thru', 'themselves', 'hundred', 'was', 'sincere', 'empty', 'more', 'himself', 'elsewhere', 'mostly', 'on', 'fire', 'am', 'becoming', 'hereby', 'amongst', 'else', 'part', 'everywhere', 'too', 'herself', 'former', 'those', 'he', 'me', 'myself', 'made', 'twenty', 'these', 'bill', 'cant', 'us', 'until', 'besides', 'nevertheless', 'below', 'anywhere', 'nine', 'can', 'of', 'your', 'toward', 'my', 'something', 'and', 'whereafter', 'whenever', 'give', 'almost', 'wherever', 'is', 'describe', 'beforehand', 'herein', 'an', 'as', 'itself', 'at', 'have', 'in', 'seem', 'whence', 'ie', 'any', 'fill', 'again', 'hasnt', 'inc', 'thereby', 'thin', 'no', 'perhaps', 'latter', 'meanwhile', 'when', 'detail', 'same', 'wherein', 'beside', 'also', 'that', 'other', 'take', 'which', 'becomes', 'you', 'if', 'nobody', 'see', 'though', 'may', 'after', 'upon', 'most', 'hereupon', 'eight', 'but', 'serious', 'nothing', 'such', 'why', 'a', 'off', 'whereby', 'third', 'i', 'whole', 'noone', 'sometimes', 'well', 'amoungst', 'yours', 'their', 'rather', 'without', 'so', 'five', 'the', 'first', 'whereas', 'once']

vectorizer = CountVectorizer(stop_words=stop_words)

x = vectorizer.fit_transform(corpus)

bow = vectorizer.vocabulary_
print(bow)

{'open': 37, 'space': 48, 'lisbon': 31, 'close': 17, 'airport': 4, 'lisboa': 30, 'junto': 27, 'expo': 24, 'gare': 26, 'oriente': 38, 'beautiful': 12, 'apt': 7, 'area': 8, 'encarnação': 22, 'quartos': 43, '1bd': 0, 'near': 36, 'aeroporto': 2, 'nações': 35, 'cosy': 18, 'apartment': 6, 'bedroom': 13, 'breakfast': 15, 'room': 46, 'bathroom': 11, 'private': 41, 'floor': 25, 'kitchen': 28, 'living': 32, 'double': 20, '2km': 1, 'beds': 14, 'próximo': 42, 'luminoso': 33, 'espaço': 23, 'verde': 53, 'em': 21, 'redor': 45, 'suite': 50, 'privat': 40, 'bathr': 10, 'amazing': 5, 'lisb': 29, 'view': 54, 'cozy': 19, 'meo': 34, 'arena': 9, 'aiport': 3, 'subway': 49, 'bus': 16, 'use': 52, 'pleasant': 39, 'sympathy': 51, 'quiet': 44, 'rooms': 47}


In [37]:
term_freq = x.toarray()
print(term_freq)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [167]:
bow_100 = pd.DataFrame(list(bow.items()), columns = ['Word',"Count"])
bow_100["Rank"] = bow_100['Count'].rank(ascending=False).astype('int')
bow_100 = bow_100[["Rank","Word","Count"]]
bow_100.sort_values("Count", ascending=False)

#bow_100.sort_values("Count", ascending=False)

Rank        Word  Count
43     1        view     54
35     2       verde     53
50     3         use     52
52     4    sympathy     51
38     5       suite     50
48     6      subway     49
1      7       space     48
54     8       rooms     47
23     9        room     46
37    10       redor     45
53    11       quiet     44
14    12     quartos     43
32    13     próximo     42
25    14     private     41
39    15      privat     40
51    16    pleasant     39
9     17     oriente     38
0     18        open     37
16    19        near     36
18    20      nações     35
45    21         meo     34
33    22    luminoso     33
28    23      living     32
2     24      lisbon     31
5     25      lisboa     30
42    26        lisb     29
27    27     kitchen     28
6     28       junto     27
8     29        gare     26
26    30       floor     25
7     31        expo     24
34    32      espaço     23
13    33  encarnação     22
36    34          em     21
29    35      double     20
44    36        cozy     19
19    37        cosy     18
3     38       close     17
49    39         bus     16
22    40   breakfast     15
31    41        beds     14
21    42     bedroom     13
10    43   beautiful     12
24    44    bathroom     11
40    45       bathr     10
46    46       arena      9
12    47        area      8
11    48         apt      7
20    49   apartment      6
41    50     amazing      5
4     51     airport      4
47    52      aiport      3
17    53   aeroporto      2
30    54         2km      1
15    55         1bd      0

# BAG OF WORDS - REFERENCE

In [ ]:
corpus = np.array(())
corpus = (np.array(np.concatenate([open(x, "r").readlines() for x in name_agg]))).tolist()
print(corpus)
vectorizer = CountVectorizer()

x = vectorizer.fit_transform(corpus)

bow = vectorizer.vocabulary_
print(bow)

# bag_of_words = vectorizer.get_feature_names()
# print(bag_of_words)

term_freq = x.toarray()
print(term_freq)


#corpus = sklearn.feature_extraction.text.CountVectorizer(docs, stop_words = stop_words)
#print(corpus)

# --------------------------------------------------------------------------------------------------

# DATA FOR ROOMTYPE

In [34]:
drop_list = ["city", "accommodates", "name", "reviews", "overall_satisfaction"]
price = clean_data.drop(drop_list, axis = 1)
price.head()

room_type       neighborhood  bedrooms  price
0  shared room      santo antónio       1.0   30.0
1  shared room     avenidas novas       1.0   39.0
2  shared room  santa maria maior       1.0   39.0
3  shared room     avenidas novas       1.0   37.0
4  shared room            arroios       1.0   96.0

In [36]:
price['price/br'] = price['price']/price["bedrooms"]
price.head(20)

room_type       neighborhood  bedrooms  price  price/br
0   shared room      santo antónio       1.0   30.0      30.0
1   shared room     avenidas novas       1.0   39.0      39.0
2   shared room  santa maria maior       1.0   39.0      39.0
3   shared room     avenidas novas       1.0   37.0      37.0
4   shared room            arroios       1.0   96.0      96.0
5   shared room   campo de ourique       1.0   90.0      90.0
6   shared room             lumiar       1.0   96.0      96.0
7   shared room  parque das nações       1.0   84.0      84.0
8   shared room     avenidas novas       1.0   66.0      66.0
9   shared room            areeiro       1.0   58.0      58.0
10  shared room  parque das nações       1.0   48.0      48.0
11  shared room            areeiro       1.0   24.0      24.0
12  shared room            areeiro       1.0   23.0      23.0
13  shared room            olivais       1.0   15.0      15.0
14  shared room          campolide       1.0   12.0      12.0
15  shared room       misericórdia       1.0   27.0      27.0
16  shared room     avenidas novas       1.0   18.0      18.0
17  shared room  santa maria maior       1.0   12.0      12.0
18  shared room           alvalade       1.0   38.0      38.0
19  shared room       misericórdia       1.0   39.0      39.0

# SWITCH ROOM TYPE TO VARIABLE

In [39]:
drop_price = ["price"]
price2 = price.drop(drop_price, axis = 1)
price3 = price2.pivot_table(index = ["neighborhood","bedrooms"], columns = ["room_type"])
price3.head(20)

price/br                         
room_type             entire home/apt private room shared room
neighborhood bedrooms                                         
ajuda        0.0                  inf          NaN         NaN
             1.0            51.041667    30.523810   18.000000
             2.0            34.825000          NaN         NaN
             3.0            32.000000          NaN         NaN
             4.0            86.250000          NaN         NaN
             9.0            25.444444          NaN         NaN
alcântara    0.0                  inf          NaN         NaN
             1.0            59.704918    42.970588         NaN
             2.0            44.818182          NaN         NaN
             3.0            28.777778          NaN         NaN
             4.0            33.416667          NaN         NaN
             6.0            40.000000          NaN         NaN
alvalade     0.0                  inf          inf         NaN
             1.0            62.218750    34.643836   29.500000
             2.0            36.775862    22.000000         NaN
             3.0            37.100000          NaN         NaN
             4.0            21.083333          NaN         NaN
             5.0            49.900000          NaN         NaN
areeiro      0.0                  NaN          inf         NaN
             1.0            70.325000    32.312500   20.642857